apiVersion: v1
kind: PersistentVolume
metadata:
  name: build-volume
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volumes/build"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
