apiVersion: v1
kind: Secret
metadata:
  name: github-deploy-key
  annotations:
    tekton.dev/git-0: github.com 
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ENTER REAL PRIVATE KEY HERE
    -----END OPENSSH PRIVATE KEY-----

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-role
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
secrets:
  - name: github-deploy-key

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildbot-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer-role
subjects:
- kind: ServiceAccount
  name: build-bot
