apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-aliases
  namespace: kube-system
  labels:
    kubernetes.io/minikube-addons: registry-aliases
    addonmanager.kubernetes.io/mode: Reconcile
data:
  # Add additonal hosts seperated by new-line
  registryAliases: >-
    registry.local
  # default registry address in minikube when enabled via minikube addons enable registry
  registrySvc: registry.kube-system.svc.cluster.local

---

apiVersion: v1
kind: ServiceAccount
metadata:
   name: registry-aliases-sa
   namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: registry-aliases-crb
subjects:
- kind: ServiceAccount
  name: registry-aliases-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: registry-aliases-hosts-update
  namespace: kube-system
  labels:
    kubernetes.io/minikube-addons: registry-aliases
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: registry-aliases-hosts-update
  template:
    metadata:
      labels:
        app: registry-aliases-hosts-update
    spec:
      initContainers:
        - name: update
          image: registry.fedoraproject.org/fedora
          volumeMounts:
            - name: etchosts
              mountPath: /host-etc/hosts
              readOnly: false
          env:
            - name: REGISTRY_ALIASES
              valueFrom:
                configMapKeyRef:
                  name: registry-aliases
                  key: registryAliases
          command:
            - bash
            - -ce
            - |
              NL=$'\n'
              TAB=$'\t'
              HOSTS="$(cat /host-etc/hosts)"
              [ -z "$REGISTRY_SERVICE_HOST" ] && echo "Failed to get hosts entry for default registry" && exit 1;
              for H in $REGISTRY_ALIASES; do                
                echo "$HOSTS" | grep "$H"  || HOSTS="$HOSTS$NL$REGISTRY_SERVICE_HOST$TAB$H";
              done;
              echo "$HOSTS" | diff -u /host-etc/hosts - || echo "$HOSTS" > /host-etc/hosts
              echo "Done."
      containers:
        - name: pause-for-update
          image: gcr.io/google_containers/pause-amd64:3.1
      terminationGracePeriodSeconds: 30
      volumes:
        - name: etchosts
          hostPath:
            path: /etc/hosts

---

apiVersion: batch/v1
kind: Job
metadata:
  name: registry-aliases-patch-core-dns
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      serviceAccountName: registry-aliases-sa
      volumes:
       - name: minikube
         hostPath: 
           path: /var/lib/minikube/binaries
      containers:
       - name: core-dns-patcher
         image:  quay.io/rhdevelopers/core-dns-patcher
         imagePullPolicy: IfNotPresent
         # using the kubectl from the minikube instance
         volumeMounts:
           - mountPath: /var/lib/minikube/binaries
             name: minikube
             readOnly: true
      restartPolicy: Never
  backoffLimit: 4