apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-probes-demo
  labels:
    app: k8s-probes-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-probes-demo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-probes-demo
    spec:
      containers:
      - name: k8s-probes-demo
        image: $IMAGE
        ports:
        - name: 8080-tcp
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080-tcp
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080-tcp
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080-tcp
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
